### ISSUE TITLE
User Epic - Club Directory

### ISSUE THREAD

**Issue by pranav-maddali** [mikezhan88/Rate-My-Club#3]
## Epic
As a user, I want to be able to browse all clubs at my school

## User Stories
- [ ] As a user, I want to be able to search for a club by name
- [ ] As a user, I want to be able to view a list of all clubs
- [ ] As a user, I want to be able to filter clubs
