### ISSUE TITLE
User Epic - View Club Page

### ISSUE THREAD

**Issue by pranav-maddali** [mikezhan88/Rate-My-Club#4]
## Epic
As a user, I want to be able to view a specific club's page and associated info

## User Stories
- [ ] As a user, I want to be able to view reviews associated with the club
- [ ] As a user, I want to be able to view a club's overall rating
- [ ] As a user, I want to be able to view a description provided by the club
