### ISSUE TITLE
User Epic - Registered User 

### ISSUE THREAD

**Issue by pranav-maddali** [mikezhan88/Rate-My-Club#5]
## Epic
As a user, I want to interact with clubs

## User Stories
- [ ] As a user, I want to log in with my credentials
- [ ] As a user, I want to bookmark a specific club
- [ ] As a user, I want to write reviews for a specific club
