### ISSUE TITLE
User Epic - Landing Page

### ISSUE THREAD

**Issue by nityasimhadri** [mikezhan88/Rate-My-Club#65]
## Epic
As a user, I want to be able to view a landing page that allows easy and clear access to other features through the page and the navigation bar.

## User Stories
- [ ] As a user, I want to view the landing page.
- [ ] As a user, I want to access the nav bar from the landing page.
- [ ] As a user, I want to access a club directory of all clubs.
- [ ] As a user, I want access to club search from the landing page.
- [ ] As a registered user, I want to access my profile from the landing page.
