### ISSUE TITLE
Club/User Epic - Navigation Bar on all Pages

### ISSUE THREAD

**Issue by nityasimhadri** [mikezhan88/Rate-My-Club#66]
## Epic
As a user, I want to be able to access a navigation bar, with redirect access, from any page that I am on.

## User Stories
- [ ] As a user and a club, I want to be able to access the landing page through the navigation bar.
- [ ] As a new club, I want to be able to register through the navigation bar.
- [ ] As a registered user, I want to be able to login through the navigation bar.
- [ ] As a registered user, I want to be able to view my profile after logged in.
