### ISSUE TITLE
Club Epic - Register Page

### ISSUE THREAD

**Issue by nityasimhadri** [mikezhan88/Rate-My-Club#67]
## Epic
As a club, I want to be able to register my club with all my information.

## User Stories
- [ ] As a club, I want to be able to enter my club name.
- [ ] As a club, I want to be able to enter my club information and description.
- [ ] As a club, I want to be able to indicate my commitment level and size amongst options.
